/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USer
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hot_package = new javax.swing.JButton();
        trip_forerign = new javax.swing.JButton();
        make_own_trip = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        classic_package = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("Home Page");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        hot_package.setBackground(new java.awt.Color(0, 0, 0));
        hot_package.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hot-package-logo-symbol-icon-260nw-1796112262.jpg"))); // NOI18N
        hot_package.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hot_packageActionPerformed(evt);
            }
        });
        getContentPane().add(hot_package, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 140, -1));

        trip_forerign.setBackground(new java.awt.Color(0, 0, 0));
        trip_forerign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/new.jpg"))); // NOI18N
        getContentPane().add(trip_forerign, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 140, -1));

        make_own_trip.setBackground(new java.awt.Color(0, 0, 0));
        make_own_trip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/make ur own.jpg"))); // NOI18N
        make_own_trip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                make_own_tripActionPerformed(evt);
            }
        });
        getContentPane().add(make_own_trip, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 140, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Setting.jpg"))); // NOI18N
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 380, 140, -1));

        classic_package.setBackground(new java.awt.Color(0, 0, 0));
        classic_package.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/classic.jpg"))); // NOI18N
        classic_package.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classic_packageActionPerformed(evt);
            }
        });
        getContentPane().add(classic_package, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 140, 150));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/premium.jpg"))); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 160, 140, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Homepage.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hot_packageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hot_packageActionPerformed
        // TODO add your handling code here:
        HotPackage hot_package = new HotPackage();
        hot_package.setVisible(true);
    }//GEN-LAST:event_hot_packageActionPerformed

    private void classic_packageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classic_packageActionPerformed
        // TODO add your handling code here:
        // classic_package 
    }//GEN-LAST:event_classic_packageActionPerformed

    private void make_own_tripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_make_own_tripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_make_own_tripActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton classic_package;
    private javax.swing.JButton hot_package;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton make_own_trip;
    private javax.swing.JButton trip_forerign;
    // End of variables declaration//GEN-END:variables
}
