/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USer
 */
public class HotPackage extends javax.swing.JFrame {

    String email;

    /**
     * Creates new form HotPackage
     */
    public HotPackage(String _email) {
        initComponents();
        this.email = _email;
        helloEmail.setText("Hello, " + email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helloEmail = new javax.swing.JButton();
        cox_hot_pack = new javax.swing.JButton();
        kaptai_hot_pack = new javax.swing.JButton();
        saint_hot_pack = new javax.swing.JButton();
        sundarban_hot_pack = new javax.swing.JButton();
        bandarban_hot_pack = new javax.swing.JButton();
        sajek_hot_pack = new javax.swing.JButton();
        back = new javax.swing.JButton();
        background_cover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helloEmail.setBackground(new java.awt.Color(0, 0, 0));
        helloEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        helloEmail.setForeground(new java.awt.Color(255, 255, 255));
        helloEmail.setText("jButton1");
        helloEmail.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                helloEmailInputMethodTextChanged(evt);
            }
        });
        getContentPane().add(helloEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 50, -1, -1));

        cox_hot_pack.setBackground(new java.awt.Color(0, 0, 0));
        cox_hot_pack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cox's button.jpg"))); // NOI18N
        cox_hot_pack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cox_hot_packActionPerformed(evt);
            }
        });
        getContentPane().add(cox_hot_pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 142, -1));

        kaptai_hot_pack.setBackground(new java.awt.Color(0, 0, 0));
        kaptai_hot_pack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kaptai button.jpg"))); // NOI18N
        kaptai_hot_pack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaptai_hot_packActionPerformed(evt);
            }
        });
        getContentPane().add(kaptai_hot_pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 141, -1));

        saint_hot_pack.setBackground(new java.awt.Color(0, 0, 0));
        saint_hot_pack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/saint button.jpg"))); // NOI18N
        saint_hot_pack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saint_hot_packActionPerformed(evt);
            }
        });
        getContentPane().add(saint_hot_pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 140, -1));

        sundarban_hot_pack.setBackground(new java.awt.Color(0, 0, 0));
        sundarban_hot_pack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sundarban button.jpg"))); // NOI18N
        sundarban_hot_pack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sundarban_hot_packActionPerformed(evt);
            }
        });
        getContentPane().add(sundarban_hot_pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 140, -1));

        bandarban_hot_pack.setBackground(new java.awt.Color(0, 0, 0));
        bandarban_hot_pack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bandarban button.jpg"))); // NOI18N
        bandarban_hot_pack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandarban_hot_packActionPerformed(evt);
            }
        });
        getContentPane().add(bandarban_hot_pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 140, -1));

        sajek_hot_pack.setBackground(new java.awt.Color(0, 0, 0));
        sajek_hot_pack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sajek button.jpg"))); // NOI18N
        sajek_hot_pack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sajek_hot_packActionPerformed(evt);
            }
        });
        getContentPane().add(sajek_hot_pack, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 140, -1));

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        background_cover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Hotpackage.jpg"))); // NOI18N
        background_cover.setText("jLabel1");
        getContentPane().add(background_cover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cox_hot_packActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cox_hot_packActionPerformed
        // TODO add your handling code here:
        CoxHotPack cox_hot_pack = new CoxHotPack(email);
        cox_hot_pack.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_cox_hot_packActionPerformed

    private void saint_hot_packActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saint_hot_packActionPerformed
        // TODO add your handling code here:
        SaintHotPack saint_hot_pack = new SaintHotPack(email);
        saint_hot_pack.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_saint_hot_packActionPerformed

    private void bandarban_hot_packActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandarban_hot_packActionPerformed
        // TODO add your handling code here:
        BandarbanHotPack bandarban_hot_pack = new BandarbanHotPack(email);
        bandarban_hot_pack.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bandarban_hot_packActionPerformed

    private void kaptai_hot_packActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaptai_hot_packActionPerformed
        // TODO add your handling code here:
        KaptaiHotPack kaptai_hot_pack = new KaptaiHotPack(email);
        kaptai_hot_pack.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_kaptai_hot_packActionPerformed

    private void sundarban_hot_packActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sundarban_hot_packActionPerformed
        // TODO add your handling code here:
        SundarbanHotPack sundarban_hot_pack = new SundarbanHotPack(email);
        sundarban_hot_pack.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_sundarban_hot_packActionPerformed

    private void sajek_hot_packActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sajek_hot_packActionPerformed
        // TODO add your handling code here:
        SajekHotPack sajek_hot_pack = new SajekHotPack(email);
        sajek_hot_pack.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_sajek_hot_packActionPerformed

    private void helloEmailInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_helloEmailInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_helloEmailInputMethodTextChanged

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotPackage("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background_cover;
    private javax.swing.JButton bandarban_hot_pack;
    private javax.swing.JButton cox_hot_pack;
    private javax.swing.JButton helloEmail;
    private javax.swing.JButton kaptai_hot_pack;
    private javax.swing.JButton saint_hot_pack;
    private javax.swing.JButton sajek_hot_pack;
    private javax.swing.JButton sundarban_hot_pack;
    // End of variables declaration//GEN-END:variables
}
